NetRom.Weather.Web/Models/ErrorViewModel.cs
namespace NetRom.Weather.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetRom.Weather.Web/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using NetRom.Weather.Application.Models;
using NetRom.Weather.Application.Services;

namespace NetRom.Weather.Web.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityService _cityService;

        private readonly ILogger<CityController> _logger;

        public CityController(ILogger<CityController> logger, ICityService cityService)
        {
            _logger = logger;
            _cityService = cityService;
        }

        //Note: Enpoint pentru a afisa lista cu toate orasele
        public async Task<IActionResult> Index()
        {
            var result = await _cityService.GetAllAsync();
            return View(result);
        }

        //Note: Enpoint pentru a creea un nou oras
        [HttpPost]
        public async Task<IActionResult> Create(CityModelForCreation cityModelForCreation)
        {
            await _cityService.CreateAsync(cityModelForCreation);

            return RedirectToAction(nameof(Index));
        }

        //Note: Enpoint pentru a creea un oras nou
        public async Task<IActionResult> Delete(Guid id)
        {
            await _cityService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        //Note: Endpoint pentru a updata un oras existent
        public async Task<IActionResult> Edit(CityModel cityModel)
        {
            if (!ModelState.IsValid)
            {
                return View(cityModel);
            }

            var result = await _cityService.UpdateAsync(cityModel);

            return RedirectToAction(nameof(Index));
        }

        //Note: Endpoint pentru a obtine view-ul de Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await _cityService.GetByIdAsync(id);

            return View(model);
        }
    }
}

NetRom.Weather.Web/Views/City/Create.cshtml
@model NetRom.Weather.Application.Models.CityModelForCreation

@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h1>Create</h1>
    <h4>City</h4>
</div>

<hr />
<div class="row" style="display:flex;justify-content:center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="margin-bottom:10px">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom:10px">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom:10px">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:flex;align-content:center;justify-content:space-between">
                <input type="submit" value="Create" class="btn btn-primary" />
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NetRom.Weather.Web/Views/City/Edit.cshtml
@model NetRom.Weather.Application.Models.CityModel

@{
    ViewData["Title"] = "Edit";
}

<div class="text-center">
    <h1>Edit</h1>
    <h4>City</h4>
</div>


<hr />
<div class="row" style="display:flex;justify-content:center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="margin-bottom:10px">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom:10px">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom:10px">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:flex;align-content:center;justify-content:space-between">
                <input type="submit" value="Save" class="btn btn-primary" />
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

NetRom.Weather.Web/Views/City/Index.cshtml
@model IEnumerable<CityModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">My Cities</h1>
</div>

<a class="btn btn-lg btn-primary active" asp-controller="City" asp-action="Create">Create</a>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>@nameof(CityModel.Name)</th>
            <th>@nameof(CityModel.Latitude)</th>
            <th>@nameof(CityModel.Longitude)</th>
            <th>@nameof(CityModel.Temperature)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var city in Model)
        {
            <tr>
                <td></td>
                <td>@city.Name</td>
                <td>@city.Latitude</td>
                <td>@city.Longitude</td>
                <td>@city.Temperature</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@city.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@city.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

NetRom.Weather.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetRom.Weather.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetRom.Weather.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetRom.Weather.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NetRom.Weather.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>